config/routes.rb
Rails.application.routes.draw do
  require 'admin_constraint'
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  resources :posts do
    resources :comments
  end

  resources :users do
    get :reset_password, as: :reset_password
  end

  resources :newsletter_signups
  
  get 'settings', to: 'users#edit', as: 'settings'
  get 'register', to: 'users#new', as: 'register'
  post :register, to: 'users#create'
  get 'login', to: 'sessions#new', as: 'login'
  post :login, to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :comments

  resource :sessions, only: [:create, :destroy]

  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  get 'admin', to: 'pages#admin'

  namespace :admin, module: 'admin' do
    resources :users
    resources :posts
    resources :newsletter_signups
  end

  get 'dashboard', to: 'pages#dashboard'
  get 'follow', to: 'pages#follow'
  post 'slack_invite', to: 'pages#slack_invite'

  get "password_resets/new"
  get 'et/:token/*path', to: 'email_token#login_and_redirect'
  resources :password_resets, only: [:create, :edit]

  root to: 'pages#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :bigint           not null, primary key
#  email                   :string
#  username                :string
#  first_name              :string
#  last_name               :string
#  password_digest         :string
#  admin                   :boolean
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  newsletter_signed_up_at :datetime
#

class User < ApplicationRecord
  include TimeScopes

  has_secure_password

  has_many :posts

  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  VALID_USERNAME_REGEX = /\A[0-9a-z_-]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 5, maximum: 300 }, on: :create

  before_save :set_username
  after_create :send_slack_invite

  has_many :comments

  scope :newsletter_subscribed, -> { where.not(newsletter_signed_up_at: nil) }

  def to_param
    username
  end

  def full_name
    if first_name && last_name
      [first_name, last_name].join(" ")
    elsif !first_name
      last_name
    elsif !last_name
      first_name
    else
      "#{first_name} #{last_name}"
    end
  end

  def send_welcome_email
    UserMailer.welcome(id).deliver_now
  end

  def send_password_reset
    SendPasswordResetMailerJob.perform_later(id)
  end

  def send_slack_invite
    SlackInviter.send_slack_invite(email)
  end

  private

    def set_username
      self.username = self.email[/^[^@]+/]
    end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :admin_only

    def index
      @users = User.all
        .order(id: :desc)
        .paginate(page: params[:page], per_page: 50)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :fetch_user, only: [
    :show, :edit, :update, :destroy, :delete_image_attachment, :drafts
  ]
  before_action :authenticate!, only: [:drafts]
  before_action :check_if_signed_in, only: [:new]
  before_action :admin_only, only: [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    @user.newsletter_signed_up_at = Time.now if user_params[:newsletter_signed_up_at]

    if @user.save
      login(@user)
      redirect_to after_sign_in_path, notice: "Thanks! You'll receive a Slack invite shortly, and now you can comment on blog posts too. ✨"
    else
      msg = @user.errors.messages.map{|m| m[1] }.join(", ")
      redirect_back(fallback_location: root_path, notice: "Oops, there was an error: #{msg}")
    end
  end

  def show
  end

  def drafts
    @posts = @user.posts.order('created_at DESC')
  end

  def edit
    if current_user
      @user = current_user

    elsif !correct_user?(@user)
      redirect_to root_path, notice: "Oops, you can't view that page."
    end

  end

  def update
    respond_to do |format|
      if @user.update(user_params)

        # @user.avatar.attach(user_params[:avatar])

        format.html { redirect_to edit_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_image_attachment
    @user.avatar.purge_later
    respond_to do |format|
      format.html { redirect_to settings_path, notice: 'Image was successfully destroyed.' }
    end
  end

  def reset_password
    flash[:notice] = "You're in. Please change your password for next time!"
    redirect_to edit_user_path(current_user, anchor: 'password')
  end

  private

    def fetch_user
      @user ||= begin
        User.find_by_username(params[:id] || params[:user_id])
        rescue ActiveRecord::RecordNotFound => e
          # If admin, attempt to lookup by id
          if user_is_admin?
            User.find params[:id]
          else
            raise e
          end
        end
    end

    def correct_user?(user)
      return user if current_user?(user) || current_user.admin?
    end

    def user_is_admin?
      current_user && current_user.admin?
    end

    def user_params
      params.require(:user).permit(
        :first_name, :last_name, :email, :password, :username, :avatar, :newsletter_signed_up_at
      ).to_h
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.slim
.user-form
  = form_for(user) do |f|
    .field
      = f.label :first_name
      = f.text_field :first_name

    .field
      = f.label :last_name
      = f.text_field :last_name

    .field
      = f.label :username
      = f.text_field :username

    .field
      = f.label :email
      = f.text_field :email
    
    br
    hr
    br

    .field
      = f.label :password
      = f.password_field :password
    
    .actions.mvg
      = f.submit "Save Changes", class: "btn btn-primary btn-lg"
    

app/views/users/edit.html.slim
#user-edit
  .container
    .row
      .col-md-8
        h4 User Settings
        p.muted Make changes to your user account below.

        = render 'user_form', user: @user

app/views/users/index.html.slim
.container

  h1 Users

  table
    thead
      tr
        th colspan="3"

    tbody
      - @users.each do |user|
        tr
          td = link_to 'Show', user
          td = link_to 'Edit', edit_user_path(user)
          td = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

  = link_to 'New User', new_user_path

app/views/users/new.html.slim
.signup
  .container
    .row
      .col-md-6
        h1 Create an account
        br
        p Welcome friend,
        p Please create an account to comment on blog posts. 
        p When you sign up, you'll receive an invite to our Slack channel (#{link_to "http://jelly-community.slack.com", "http://jelly-community.slack.com"}).
        p
          | Our Slack has a #{link_to "Code of Conduct", "https://gitlab.com/cindyw/jelly/wikis/Jelly-Community-Slack-Rules"} which you can browse, but please be nice. We are gentle creatures.

        p
          | Already have an account? 
          = link_to "Log in", login_path


      .col-md-6
        = form_for @user do |f|
          .field
            label
              | First name
              = f.text_field :first_name, required: true
          .field
            label
              | Last name
              = f.text_field :last_name, required: true
          .field
            label
              | Email
              = f.email_field :email, required: true
          
          .field
            label
              | Password
              = f.password_field :password, required: true, minlength: 5, maxlength: 300

          .field.mbg
            checkbox
              label
                | Sign up for our newsletter?
                .holder
                  = f.check_box :newsletter_signed_up_at, {}, true, false
                  span class="checkmark"
                  span class="message animated fadeIn"
          
          .actions
            = f.submit "Sign Up", class: "btn btn-primary btn-lg mt"

        

app/views/users/password_reset.html.slim
.container.password-reset-container
  .col-md-85
    h1.password-reset-heading Reset Password
    p.password-reset-instructions Enter the email address that you used to sign up and we'll send you a link to reset your password.
    p.password-reset-instructions
      | If you need additional help, don't hesitate to #{link_to("contact us", new_feedback_path)}!
    = form_tag password_resets_path, :method => :post, class: 'large form' do
      = label_tag :email, "Email:"
      = email_field_tag :email, params[:email], placeholder: "albert@einstein.com"
      br
      = submit_tag 'Send Password Reset Email', class: 'btn btn-primary'

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>