config/routes.rb
Rails.application.routes.draw do
  require 'admin_constraint'
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  resources :posts do
    resources :comments
  end

  resources :users do
    get :reset_password, as: :reset_password
  end

  resources :newsletter_signups
  
  get 'settings', to: 'users#edit', as: 'settings'
  get 'register', to: 'users#new', as: 'register'
  post :register, to: 'users#create'
  get 'login', to: 'sessions#new', as: 'login'
  post :login, to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :comments

  resource :sessions, only: [:create, :destroy]

  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  get 'admin', to: 'pages#admin'

  namespace :admin, module: 'admin' do
    resources :users
    resources :posts
    resources :newsletter_signups
  end

  get 'dashboard', to: 'pages#dashboard'
  get 'follow', to: 'pages#follow'
  post 'slack_invite', to: 'pages#slack_invite'

  get "password_resets/new"
  get 'et/:token/*path', to: 'email_token#login_and_redirect'
  resources :password_resets, only: [:create, :edit]

  root to: 'pages#index'
end

app/views/pages/_home_post.html.slim
.home-post
  h1 = link_to post.title, post_path(post)

  p.date
  	= "#{post.created_at.strftime("%b %d, %Y")}"

  p
  	= truncate(strip_tags(post.content.to_s), length: 500, separator: '...')

		/ - if post.body
		/ 	= post.body.truncate(600, separator: "...").html_safe

  = link_to "Read more", post_path(post)

app/views/pages/admin.html.slim
- content_for(:title) { "About" }

.pages
  .container.mbg
    .row
      .col-md-8
        h1 Admin Dashboard

        ul
          li = link_to "Users", admin_users_path
          li = link_to "Posts", admin_posts_path
          li = link_to "Newsletter Signups", admin_newsletter_signups_path

app/views/pages/dashboard.html.slim
#dashboard.container
  .row
    .col-md-9
      h2 Recent Activity

      - if @posts.any?
        - @posts.each do |post|

          .mtg
            .author

              span.muted
                | #{post.user.first_name} published
                / - if post.project.present?
                /   | in #{post.project.title}

            = link_to post do
              .post
                .title
                  = post.title
                .preview
                  = post.body.truncate(120, separator: "...").html_safe

                .date
                  | #{time_ago_in_words(post.created_at)} ago
      - else
        .muted no posts yet!

app/views/pages/follow.html.slim
= content_for(:title) { "Join our newsletter and slack!" }

.signup
  .container
    .row.mbg
      .col-md-6
        h1 Get our newsletter
        br
        p We're documenting our process and steps in our blog, and you can get our progress by email whenever we post something.
      .col-md-6
        = form_for @newsletter_signup do |f|
          .field.smol-form
            label
              | Email for newsletter
            = f.email_field :email, required: true, placeholder: "your email address"
            = f.submit "Sign Up", class: "btn btn-primary btn-lg mt"

    .row.mvg
      .col-md-6
        h1 Join our Slack chat
        br
        p To join our Slack community chat, you'll have to receive an invite to the group by putting your email into the box: #{link_to "http://jelly-community.slack.com", "http://jelly-community.slack.com"}
        p
          | Our Slack has a #{link_to "Code of Conduct", "https://gitlab.com/cindyw/jelly/wikis/Jelly-Community-Slack-Rules"} which you can browse, but please be nice. We are gentle creatures.

      .col-md-6
        = form_for :slack_invite, url: slack_invite_path, method: :post do |f|
          .field.smol-form
            label
              | Email for slack invite
            = f.email_field :email, required: true, placeholder: "your email address"
            = f.submit "Sign Up", class: "btn btn-primary btn-lg mt"

app/views/pages/index.html.erb
<% content_for(:title) { "⚗️ Jelly Labs PBC" } %>
<% content_for(:meta_description) { "A new kind of science" } %>

<div class="container">
  <div class="row">
    <div class="home">
      <div class="header header-remove">
        <h1 class="">
          Jelly Labs
        </h1>
        <p>
          We're Denny and Cindy, working on building equitable platforms for scientists.
        </p>

        <div class="block">
          <a class="newsletter" href=<%= follow_path %>>
            Sign up for our newsletter
          </a>

          <div class="social-icons">
            <span>Join us!</span>
            <span>
              <% if current_user %>
                <a href="http://jelly-community.slack.com"><i class="fa fa-slack mlm"></i></a>
              <% else %>
                <a href=<%= follow_path %>><i class="fa fa-slack mlm"></i></a>
              <% end %>
            </span>
            <span>
              <a href="http://twitter.com/jellypbc"><i class="fa fa-twitter mlm"></i></a>
            </span>
            <span>
              <a href="https://github.com/jellypbc"><i class="fa fa-github mlm"></i></a>
            </span>
          </div>
        </div>
      </div>

      <div class="header hidden">
        <canvas id='canvas' resize hidpi="off" background="#29D04E">
        </canvas>
        <h1 class="">
          Jelly Labs
        </h1>
        <p>
          We're Denny and Cindy, working on building equitable platforms for scientists.
        </p>

        <div class="block">
          <a class="newsletter" href=<%= follow_path %>>
            Sign up for our newsletter
          </a>

          <div class="social-icons">
            <span>Join us!</span>
            <span>
              <% if current_user %>
                <a href="http://jelly-community.slack.com"><i class="fa fa-slack mlm"></i></a>
              <% else %>
                <a href=<%= follow_path %>><i class="fa fa-slack mlm"></i></a>
              <% end %>
            </span>
            <span>
              <a href="http://twitter.com/jellypbc"><i class="fa fa-twitter mlm"></i></a>
            </span>
            <span>
              <a href="https://github.com/jellypbc"><i class="fa fa-github mlm"></i></a>
            </span>
          </div>
        </div>
      </div>

      <div class="posts">

        <% @posts.each do |post| %>

          <%= render 'home_post', post: post %>

        <% end %>

        <%= will_paginate @posts %>
      </div>


    </div>

  </div>
</div>