config/routes.rb
Rails.application.routes.draw do
  require 'admin_constraint'
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  resources :posts do
    resources :comments
  end

  resources :users do
    get :reset_password, as: :reset_password
  end

  resources :newsletter_signups
  
  get 'settings', to: 'users#edit', as: 'settings'
  get 'register', to: 'users#new', as: 'register'
  post :register, to: 'users#create'
  get 'login', to: 'sessions#new', as: 'login'
  post :login, to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :comments

  resource :sessions, only: [:create, :destroy]

  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  get 'admin', to: 'pages#admin'

  namespace :admin, module: 'admin' do
    resources :users
    resources :posts
    resources :newsletter_signups
  end

  get 'dashboard', to: 'pages#dashboard'
  get 'follow', to: 'pages#follow'
  post 'slack_invite', to: 'pages#slack_invite'

  get "password_resets/new"
  get 'et/:token/*path', to: 'email_token#login_and_redirect'
  resources :password_resets, only: [:create, :edit]

  root to: 'pages#index'
end

app/models/newsletter_signup.rb
# == Schema Information
#
# Table name: newsletter_signups
#
#  id         :bigint           not null, primary key
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class NewsletterSignup < ApplicationRecord
end

app/controllers/admin/newsletter_signups_controller.rb
module Admin
  class NewsletterSignupsController < ApplicationController
    before_action :admin_only

    def index
      @newsletter_signups = NewsletterSignup.all
        .order(id: :desc)
        .paginate(page: params[:page], per_page: 50)
    end

  end
end

app/controllers/newsletter_signups_controller.rb
class NewsletterSignupsController < ApplicationController

	def create
    @newsletter_signup = NewsletterSignup.new(newsletter_params)
    if @newsletter_signup.save
      redirect_to root_path, notice: "Thanks! You've been added to our newsletter group ✨"
    else
      msg = @newsletter_signup.errors.messages.map{|m| m[1] }.join(", ")
      redirect_back(fallback_location: root_path, notice: "Oops, there was an error: #{msg}")
    end

	end

	def update
	end

	def destroy
	end

	private
		def newsletter_params
			params.require(:newsletter_signup).permit( :email )
		end
end

app/views/admin/newsletter_signups/index.html.slim
.content.pvg.mbg
  .container.mbg
    .row
      .col-md-8
        h1 Newsletter Signups
        p #{@newsletter_signups.total_entries} newsletter signups

        .back-to = link_to "Back to Admin", admin_path
      .col-md-12
        .mvg
          table.table
            thead
              tr
                th ID
                th Email
                th Created At
            tbody
              - @newsletter_signups.each do |newsletter_signup|
                tr
                  td = link_to newsletter_signup.id, newsletter_signup_path(newsletter_signup)
                  td = newsletter_signup.email
                  td = newsletter_signup.created_at.strftime("%d %b %Y %l:%M %p")

          = will_paginate @newsletter_signups