config/routes.rb
Rails.application.routes.draw do
  require 'admin_constraint'
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web, at: '/sidekiq', constraints: AdminConstraint.new

  resources :posts do
    resources :comments
  end

  resources :users do
    get :reset_password, as: :reset_password
  end

  resources :newsletter_signups
  
  get 'settings', to: 'users#edit', as: 'settings'
  get 'register', to: 'users#new', as: 'register'
  post :register, to: 'users#create'
  get 'login', to: 'sessions#new', as: 'login'
  post :login, to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :comments

  resource :sessions, only: [:create, :destroy]

  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  get 'admin', to: 'pages#admin'

  namespace :admin, module: 'admin' do
    resources :users
    resources :posts
    resources :newsletter_signups
  end

  get 'dashboard', to: 'pages#dashboard'
  get 'follow', to: 'pages#follow'
  post 'slack_invite', to: 'pages#slack_invite'

  get "password_resets/new"
  get 'et/:token/*path', to: 'email_token#login_and_redirect'
  resources :password_resets, only: [:create, :edit]

  root to: 'pages#index'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :bigint           not null, primary key
#  title        :string
#  body         :text
#  body_json    :jsonb
#  slug         :string
#  public       :boolean
#  published_at :datetime
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  project_id   :integer
#

class Post < ApplicationRecord
  include TimeScopes
  include Slugged
  include SlugHistory
  has_rich_text :content

  slug :title, attribute: :slug
  remember_slug

  belongs_to :user

  scope :are_public, -> { where(public: true) }

  validates :title, length: { maximum: 120 }, presence: true

  has_many :comments, as: :commentable

  def to_param
    slug
  end

  def render_body
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true)
    markdown.render(body)
  end
  
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    before_action :admin_only

    def index
      @posts = Post.all
        .order(id: :desc)
        .paginate(page: params[:page], per_page: 50)
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, only: [:edit, :update, :destroy, :index, :create]
  # before_action :set_form_user, only: [:create]
  before_action :authenticate!, except: [:show]

  def index
    @posts = Post.all
      .order(created_at: :desc)
      .paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save!
      respond_to do |format|
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: {redirect_to: post_path(@post) } }
      end
    else
      respond_to do |format|
        format.html { render :new }
        # format.js { render json: {dog: "dog"}}
        # format.js { render status: :bad_request, json: { responseText: @post.errors.full_messages.first } }
        format.json { render @post.errors.messages.to_json }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update!(post_params)
        post = Post.find @post.id

        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render json: { redirect_to: post_path(post) } }
      else
        format.html { render :edit }
        format.json { render json: @post.errors.messages.to_json }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      id_or_slug = params[:id] || params[:post_id]

      @post ||= begin
        Post.find_by!(slug: id_or_slug)
      rescue
        if (post = Post.find id_or_slug)
          post
        else
          raise ActiveRecord::RecordNotFound
        end
      end
    end

    def set_form_user
      begin
        if (user_id = params[:post][:user_id]) && user_id.present?
          @user = User.find(user_id)
        elsif (user_params.any?)
          if @user = User.find_by_email(user_params[:email])
          else
            @user = User.create!(
              user_params.merge({password: 'experiment'})
            )
          end
        elsif current_user
          @user = current_user
        end
        
      rescue => e
        render(json: { error: "No user" }, status: :unprocessable_entity) and return
      end
    end


    def post_params
      params.require(:post).permit(
        :title, :description, :public, :body_json, :body, :content
      ).to_h
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
/ = react_component "SlateEditor", post: PostSerializer.new(post).serializable_hash, readOnly: false

= form_for @post do |form|
  .field
  	= form.text_field :title, class: "lrg", placeholder: "Title"
    = form.rich_text_area :content, placeholder: "My post..."
    = form.hidden_field :public, value: true
    = form.submit "Save", class: "btn btn-primary btn-lg mvg"

app/views/posts/edit.html.slim
- content_for(:title) { "Editing Post" }

/ = stylesheet_link_tag "trix"

#editor
  .container
    .post-header
      - if current_user && current_user == @post.user
        pre
          | Editing Post
          - if current_user && user_is_admin?
            | : #{@post.id}

          |&nbsp;|&nbsp;
          = link_to "Edit", edit_post_path(@post)
          span.mhs |
          = link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } 

    .row
      .col-md-12
        = render "form", post: @post

app/views/posts/index.html.slim
.container
  h1 Posts
  = link_to "New post", new_post_path, class: "btn btn-primary"

  - @posts.each do |post|
    = render 'pages/home_post', post: post
    
  = will_paginate @posts

app/views/posts/new.html.slim
- content_for(:title) { "New Post" }

#editor
  .container
    .row
      .col-md-12
        = render "form", post: @post

app/views/posts/show.html.slim
- content_for(:title) { "#{@post.title}" }
- content_for(:meta_description) { truncate(strip_tags(@post.content.to_s), length: 30, separator: '...') }

#post-show
  .container

    .post-body
      .title
        h1 = @post.title

      / = react_component "PostRenderer", post: PostSerializer.new(@post).serializable_hash
      = @post.content.to_s.html_safe

    .post-header
      - if current_user && current_user == @post.user
        span Admin | 
        = link_to "Edit", edit_post_path(@post)
        span.mhs |
        = link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } 

    .post-comments.mvg
      h3 Comments
      - if @post.comments.any?
        - @post.comments.each do |comment|
          .comment.mvm
            .comment-user
              = link_to comment.user.username, comment.user
            .comment-content = comment.content
            .date #{time_ago_in_words(comment.created_at)} ago

            - if current_user && comment.user == current_user
              = link_to [comment.commentable, comment], method: :delete, data: { confirm: 'Are you sure?' } do
                | Delete
      - else
        .no-comments
          | No comments yet

      - if current_user
        - comment = @post.comments.new
        = form_for [@post, comment] do |f|
          .field
            = f.text_area :content, rows: 3, required: true, placeholder: "Add a comment..."
          .actions
            = f.submit "Add Comment", class: "btn btn-primary"
      - else
        = link_to "Log in to comment", register_path, class: "btn btn-secondary"